"""Persistence for decisions, activity, policies, actions and runs.

Two implementations behind one interface:

* `JsonStore`   — plain files on disk. What mock mode uses, and what `make demo`
  runs on. Must work with **zero credentials**.
* `DynamoStore` — the deployed path (A7). Single-table, and it stores the same
  contract models as JSON text so both lanes parse identical bytes.

Everything crossing this boundary is a contract model from `quiet_hours_contracts`,
never a loose dict. Lane B reads the same records through its own code, so the
shapes have to be exactly the frozen ones.

Writes are atomic (temp file + `os.replace`). A run can be interrupted at any
point — a half-written decision card would strand a suspended session with no way
for the user to answer it.
"""

from __future__ import annotations

import json
import logging
import os
import uuid
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Protocol

from quiet_hours_contracts import (
    ActivityEntry,
    DecisionCard,
    DecisionResponse,
    DecisionStatus,
    Policy,
    ProposedAction,
    RiskTier,
    Run,
)

logger = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_STORE_DIR = REPO_ROOT / ".local" / "store"


def new_id(prefix: str) -> str:
    """Opaque id. Contract says consumers must not parse these, so uuid4 is fine.

    (`python-ulid` is in `pyproject.toml` but not installed in the dev env yet;
    switching later is a no-op precisely because nothing may parse these.)
    """
    return f"{prefix}_{uuid.uuid4().hex[:24]}"


def utcnow() -> datetime:
    return datetime.now(UTC)


class Store(Protocol):
    """What the agent needs from persistence. Kept small on purpose."""

    def put_action(self, action: ProposedAction) -> None: ...
    def get_action(self, action_id: str) -> ProposedAction | None: ...

    def save_decision(self, card: DecisionCard) -> None: ...
    def get_decision(self, decision_id: str) -> DecisionCard | None: ...
    def resolve_decision(
        self, decision_id: str, response: DecisionResponse
    ) -> DecisionCard | None: ...
    def list_pending_decisions(self, household_id: str) -> list[DecisionCard]: ...

    def write_activity(self, entry: ActivityEntry) -> None: ...
    def list_activity(self, household_id: str) -> list[ActivityEntry]: ...

    def list_policies(self, household_id: str) -> list[Policy]: ...
    def save_policy(self, policy: Policy) -> None: ...

    def save_run(self, run: Run) -> None: ...
    def get_run(self, run_id: str) -> Run | None: ...


class JsonStore:
    """One JSON file per record, grouped by type. Good enough for a demo."""

    def __init__(self, root: Path | str | None = None) -> None:
        self.root = Path(root or os.environ.get("QH_STORE_DIR") or DEFAULT_STORE_DIR)
        for bucket in ("actions", "decisions", "activity", "policies", "runs"):
            (self.root / bucket).mkdir(parents=True, exist_ok=True)

    # -- low-level ---------------------------------------------------------

    def _path(self, bucket: str, record_id: str) -> Path:
        # Ids are generated by us, but never let one escape its bucket.
        safe = record_id.replace("/", "_").replace("\\", "_").replace("..", "_")
        return self.root / bucket / f"{safe}.json"

    def _write(self, bucket: str, record_id: str, payload: str) -> None:
        """Atomic write. A half-written card would strand a suspended run."""
        target = self._path(bucket, record_id)
        tmp = target.with_suffix(".json.tmp")
        tmp.write_text(payload, encoding="utf-8")
        os.replace(tmp, target)

    def _read(self, bucket: str, record_id: str) -> str | None:
        target = self._path(bucket, record_id)
        if not target.exists():
            return None
        return target.read_text(encoding="utf-8")

    def _read_all(self, bucket: str) -> list[dict[str, Any]]:
        out: list[dict[str, Any]] = []
        for path in sorted((self.root / bucket).glob("*.json")):
            try:
                out.append(json.loads(path.read_text(encoding="utf-8")))
            except json.JSONDecodeError:
                logger.warning("skipping unreadable record: %s", path)
        return out

    # -- actions -----------------------------------------------------------

    def put_action(self, action: ProposedAction) -> None:
        self._write("actions", action.action_id, action.model_dump_json(indent=2))

    def get_action(self, action_id: str) -> ProposedAction | None:
        raw = self._read("actions", action_id)
        return ProposedAction.model_validate_json(raw) if raw else None

    # -- decisions ---------------------------------------------------------

    def save_decision(self, card: DecisionCard) -> None:
        self._write("decisions", card.decision_id, card.model_dump_json(indent=2))

    def get_decision(self, decision_id: str) -> DecisionCard | None:
        raw = self._read("decisions", decision_id)
        return DecisionCard.model_validate_json(raw) if raw else None

    def resolve_decision(self, decision_id: str, response: DecisionResponse) -> DecisionCard | None:
        """Mark a card answered. Idempotent — the hook may replay it on resume."""
        card = self.get_decision(decision_id)
        if card is None:
            logger.warning("resolve_decision: no card %s", decision_id)
            return None

        card.status = DecisionStatus.RESOLVED
        card.resolved_at = response.responded_at or utcnow()
        self.save_decision(card)
        return card

    def list_pending_decisions(self, household_id: str) -> list[DecisionCard]:
        return [
            card
            for raw in self._read_all("decisions")
            if (card := DecisionCard.model_validate(raw)).household_id == household_id
            and card.status is DecisionStatus.PENDING
        ]

    # -- activity ----------------------------------------------------------

    def write_activity(self, entry: ActivityEntry) -> None:
        self._write("activity", entry.entry_id, entry.model_dump_json(indent=2))

    def list_activity(self, household_id: str) -> list[ActivityEntry]:
        entries = [ActivityEntry.model_validate(raw) for raw in self._read_all("activity")]
        return sorted(
            (entry for entry in entries if entry.household_id == household_id),
            key=lambda entry: entry.occurred_at,
        )

    # -- policies ----------------------------------------------------------

    def list_policies(self, household_id: str) -> list[Policy]:
        return [
            policy
            for raw in self._read_all("policies")
            if (policy := Policy.model_validate(raw)).household_id == household_id
        ]

    def save_policy(self, policy: Policy) -> None:
        self._write("policies", policy.policy_id, policy.model_dump_json(indent=2))

    # -- runs --------------------------------------------------------------

    def save_run(self, run: Run) -> None:
        self._write("runs", run.run_id, run.model_dump_json(indent=2))

    def get_run(self, run_id: str) -> Run | None:
        raw = self._read("runs", run_id)
        return Run.model_validate_json(raw) if raw else None


def build_activity_entry(
    action: ProposedAction,
    *,
    risk: RiskTier,
    was_autonomous: bool,
    succeeded: bool,
    summary: str | None = None,
    rationale: str,
    policy_id: str | None = None,
    decision_id: str | None = None,
    error: str | None = None,
) -> ActivityEntry:
    """Build the audit line for one action.

    Every action produces one of these — autonomous or not, success or failure.
    That is a product promise, not a debugging aid (`agent/AGENTS.md`, rule 3).
    """
    return ActivityEntry(
        entry_id=new_id("ent"),
        household_id=action.household_id,
        run_id=action.run_id,
        action_id=action.action_id,
        decision_id=decision_id,
        occurred_at=utcnow(),
        summary=(summary or action.summary)[:160],
        rationale=rationale,
        risk=risk,
        was_autonomous=was_autonomous,
        policy_id=policy_id,
        succeeded=succeeded,
        error=error,
        impact=action.estimated_impact,
    )


# --------------------------------------------------------------------------
# The deployed path
# --------------------------------------------------------------------------

TABLE_NAME_ENV = "QH_TABLE_NAME"

TYPE_ACTION = "ACTION"
TYPE_DECISION = "DECISION"
TYPE_ACTIVITY = "ACTIVITY"
TYPE_POLICY = "POLICY"
TYPE_RUN = "RUN"

HOUSEHOLD_INDEX = "gsi1"
"""Name of the GSI that answers every `list_*_for_household` query."""


class StoreConfigError(RuntimeError):
    """Live mode was asked for without the configuration it requires."""


class DynamoStore:
    """Single-table DynamoDB, holding the same contract models `JsonStore` holds.

    **Key schema** (proposed — see the note at the bottom of `PROGRESS_A.md`; the
    table itself is Lane C's CDK and Lane B reads these rows, so this layout needs
    both of them to agree before it is real):

        pk            "DECISION#dec_abc"        partition: the record's own id
        sk            "DECISION#dec_abc"        same; the table is a pure key-value
                                                store for the id lookups the
                                                `Store` protocol requires
        gsi1pk        "HH#hh_demo#DECISION"     partition: one household's records
                                                of one type
        gsi1sk        "2026-08-24T07:15:00Z"    sort: chronological, so the inbox
                                                and the activity trail come back
                                                in order without a client-side sort
        body          '{"decision_id": ...}'    the contract model, as JSON text

    Two decisions in there are worth defending.

    **Ids are their own partition key.** `Store.get_decision(decision_id)` takes
    no `household_id` — Lane B's `POST /api/decisions/{id}/respond` only has the
    id from the URL. A household-partitioned table would force every read to be a
    scan or a second lookup. The household query is the secondary access pattern,
    so it goes on the secondary index.

    **The model is stored as a JSON string, not as attributes.** DynamoDB has no
    float type, and `Finding.confidence` is a float; storing attributes would mean
    a `Decimal` conversion on every write and back again on every read, in both
    Lane A's code and Lane B's, forever. Round-tripping `model_dump_json` means
    the bytes in the table are exactly the frozen contract shape and both lanes
    parse them with the same pydantic models. It costs the ability to query on an
    inner field, which nothing in the product does.

    Not covered here: pagination. Every list method takes the first page, which
    is right for a household's decisions and policies and wrong in principle for a
    year of activity. Bounded deliberately rather than accidentally — a demo
    household produces tens of rows, and an unbounded scan on stage is worse than
    a truncated list.
    """

    def __init__(self, table_name: str | None = None, *, table: Any | None = None) -> None:
        self.table_name = table_name or os.environ.get(TABLE_NAME_ENV, "").strip()
        if not self.table_name and table is None:
            raise StoreConfigError(
                f"live mode needs {TABLE_NAME_ENV}. Set QH_PROVIDER_MODE=mock to run offline."
            )

        if table is not None:
            self._table = table
        else:
            import boto3

            self._table = boto3.resource(
                "dynamodb", region_name=os.environ.get("AWS_REGION", "us-east-1")
            ).Table(self.table_name)

    # -- low-level ---------------------------------------------------------

    @staticmethod
    def _key(record_type: str, record_id: str) -> str:
        return f"{record_type}#{record_id}"

    @staticmethod
    def _household_key(record_type: str, household_id: str) -> str:
        return f"HH#{household_id}#{record_type}"

    def _put(
        self,
        record_type: str,
        record_id: str,
        *,
        household_id: str,
        sort_value: datetime,
        model: Any,
    ) -> None:
        key = self._key(record_type, record_id)
        self._table.put_item(
            Item={
                "pk": key,
                "sk": key,
                "gsi1pk": self._household_key(record_type, household_id),
                "gsi1sk": sort_value.isoformat(),
                "type": record_type,
                "body": model.model_dump_json(),
            }
        )

    def _get(self, record_type: str, record_id: str, model_cls: Any) -> Any | None:
        key = self._key(record_type, record_id)
        response = self._table.get_item(Key={"pk": key, "sk": key})
        item = response.get("Item")
        if not item:
            return None
        return model_cls.model_validate_json(item["body"])

    def _query_household(self, record_type: str, household_id: str, model_cls: Any) -> list[Any]:
        # Imported here, not at module scope: `JsonStore` is the mock-mode path
        # and mock mode must run with neither credentials nor boto3 installed.
        from boto3.dynamodb.conditions import Key

        response = self._table.query(
            IndexName=HOUSEHOLD_INDEX,
            KeyConditionExpression=Key("gsi1pk").eq(self._household_key(record_type, household_id)),
            ScanIndexForward=True,
        )
        out: list[Any] = []
        for item in response.get("Items", []):
            try:
                out.append(model_cls.model_validate_json(item["body"]))
            except (KeyError, ValueError):
                logger.warning("skipping unreadable %s row: %s", record_type, item.get("pk"))
        return out

    # -- actions -----------------------------------------------------------

    def put_action(self, action: ProposedAction) -> None:
        self._put(
            TYPE_ACTION,
            action.action_id,
            household_id=action.household_id,
            sort_value=action.created_at,
            model=action,
        )

    def get_action(self, action_id: str) -> ProposedAction | None:
        return self._get(TYPE_ACTION, action_id, ProposedAction)

    # -- decisions ---------------------------------------------------------

    def save_decision(self, card: DecisionCard) -> None:
        self._put(
            TYPE_DECISION,
            card.decision_id,
            household_id=card.household_id,
            sort_value=card.created_at,
            model=card,
        )

    def get_decision(self, decision_id: str) -> DecisionCard | None:
        return self._get(TYPE_DECISION, decision_id, DecisionCard)

    def resolve_decision(self, decision_id: str, response: DecisionResponse) -> DecisionCard | None:
        """Mark a card answered. Idempotent — the hook replays it on resume."""
        card = self.get_decision(decision_id)
        if card is None:
            logger.warning("resolve_decision: no card %s", decision_id)
            return None

        card.status = DecisionStatus.RESOLVED
        card.resolved_at = response.responded_at or utcnow()
        self.save_decision(card)
        return card

    def list_pending_decisions(self, household_id: str) -> list[DecisionCard]:
        # Status is filtered here rather than folded into `gsi1pk`. Putting it in
        # the key would make resolving a card a delete-and-reinsert across two
        # partitions, and a crash between the two would lose the card entirely.
        return [
            card
            for card in self._query_household(TYPE_DECISION, household_id, DecisionCard)
            if card.status is DecisionStatus.PENDING
        ]

    # -- activity ----------------------------------------------------------

    def write_activity(self, entry: ActivityEntry) -> None:
        self._put(
            TYPE_ACTIVITY,
            entry.entry_id,
            household_id=entry.household_id,
            sort_value=entry.occurred_at,
            model=entry,
        )

    def list_activity(self, household_id: str) -> list[ActivityEntry]:
        # `gsi1sk` is `occurred_at`, so the index returns these already ordered.
        return self._query_household(TYPE_ACTIVITY, household_id, ActivityEntry)

    # -- policies ----------------------------------------------------------

    def list_policies(self, household_id: str) -> list[Policy]:
        return self._query_household(TYPE_POLICY, household_id, Policy)

    def save_policy(self, policy: Policy) -> None:
        self._put(
            TYPE_POLICY,
            policy.policy_id,
            household_id=policy.household_id,
            sort_value=policy.created_at,
            model=policy,
        )

    # -- runs --------------------------------------------------------------

    def save_run(self, run: Run) -> None:
        self._put(
            TYPE_RUN,
            run.run_id,
            household_id=run.household_id,
            sort_value=run.started_at,
            model=run,
        )

    def get_run(self, run_id: str) -> Run | None:
        return self._get(TYPE_RUN, run_id, Run)


def build_store(mode: str | None = None) -> Store:
    """Pick a store. Mock mode is the default and needs no credentials."""
    resolved = (mode or os.environ.get("QH_PROVIDER_MODE") or "mock").strip().casefold()
    if resolved == "live":
        return DynamoStore()
    return JsonStore()
