"""Persistence for decisions, activity, policies, actions and runs.

Two implementations behind one interface:

* `JsonStore`   — plain files on disk. What mock mode uses, and what `make demo`
  runs on. Must work with **zero credentials**.
* `DynamoStore` — the deployed path. Deliberately not written yet (A7); the
  interface below is the seam it will slot into.

Everything crossing this boundary is a contract model from `quiet_hours_contracts`,
never a loose dict. Lane B reads the same records through its own code, so the
shapes have to be exactly the frozen ones.

Writes are atomic (temp file + `os.replace`). A run can be interrupted at any
point — a half-written decision card would strand a suspended session with no way
for the user to answer it.
"""

from __future__ import annotations

import json
import logging
import os
import uuid
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Protocol

from quiet_hours_contracts import (
    ActivityEntry,
    DecisionCard,
    DecisionResponse,
    DecisionStatus,
    Policy,
    ProposedAction,
    RiskTier,
    Run,
)

logger = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_STORE_DIR = REPO_ROOT / ".local" / "store"


def new_id(prefix: str) -> str:
    """Opaque id. Contract says consumers must not parse these, so uuid4 is fine.

    (`python-ulid` is in `pyproject.toml` but not installed in the dev env yet;
    switching later is a no-op precisely because nothing may parse these.)
    """
    return f"{prefix}_{uuid.uuid4().hex[:24]}"


def utcnow() -> datetime:
    return datetime.now(UTC)


class Store(Protocol):
    """What the agent needs from persistence. Kept small on purpose."""

    def put_action(self, action: ProposedAction) -> None: ...
    def get_action(self, action_id: str) -> ProposedAction | None: ...

    def save_decision(self, card: DecisionCard) -> None: ...
    def get_decision(self, decision_id: str) -> DecisionCard | None: ...
    def resolve_decision(
        self, decision_id: str, response: DecisionResponse
    ) -> DecisionCard | None: ...
    def list_pending_decisions(self, household_id: str) -> list[DecisionCard]: ...

    def write_activity(self, entry: ActivityEntry) -> None: ...
    def list_activity(self, household_id: str) -> list[ActivityEntry]: ...

    def list_policies(self, household_id: str) -> list[Policy]: ...
    def save_policy(self, policy: Policy) -> None: ...

    def save_run(self, run: Run) -> None: ...
    def get_run(self, run_id: str) -> Run | None: ...


class JsonStore:
    """One JSON file per record, grouped by type. Good enough for a demo."""

    def __init__(self, root: Path | str | None = None) -> None:
        self.root = Path(root or os.environ.get("QH_STORE_DIR") or DEFAULT_STORE_DIR)
        for bucket in ("actions", "decisions", "activity", "policies", "runs"):
            (self.root / bucket).mkdir(parents=True, exist_ok=True)

    # -- low-level ---------------------------------------------------------

    def _path(self, bucket: str, record_id: str) -> Path:
        # Ids are generated by us, but never let one escape its bucket.
        safe = record_id.replace("/", "_").replace("\\", "_").replace("..", "_")
        return self.root / bucket / f"{safe}.json"

    def _write(self, bucket: str, record_id: str, payload: str) -> None:
        """Atomic write. A half-written card would strand a suspended run."""
        target = self._path(bucket, record_id)
        tmp = target.with_suffix(".json.tmp")
        tmp.write_text(payload, encoding="utf-8")
        os.replace(tmp, target)

    def _read(self, bucket: str, record_id: str) -> str | None:
        target = self._path(bucket, record_id)
        if not target.exists():
            return None
        return target.read_text(encoding="utf-8")

    def _read_all(self, bucket: str) -> list[dict[str, Any]]:
        out: list[dict[str, Any]] = []
        for path in sorted((self.root / bucket).glob("*.json")):
            try:
                out.append(json.loads(path.read_text(encoding="utf-8")))
            except json.JSONDecodeError:
                logger.warning("skipping unreadable record: %s", path)
        return out

    # -- actions -----------------------------------------------------------

    def put_action(self, action: ProposedAction) -> None:
        self._write("actions", action.action_id, action.model_dump_json(indent=2))

    def get_action(self, action_id: str) -> ProposedAction | None:
        raw = self._read("actions", action_id)
        return ProposedAction.model_validate_json(raw) if raw else None

    # -- decisions ---------------------------------------------------------

    def save_decision(self, card: DecisionCard) -> None:
        self._write("decisions", card.decision_id, card.model_dump_json(indent=2))

    def get_decision(self, decision_id: str) -> DecisionCard | None:
        raw = self._read("decisions", decision_id)
        return DecisionCard.model_validate_json(raw) if raw else None

    def resolve_decision(self, decision_id: str, response: DecisionResponse) -> DecisionCard | None:
        """Mark a card answered. Idempotent — the hook may replay it on resume."""
        card = self.get_decision(decision_id)
        if card is None:
            logger.warning("resolve_decision: no card %s", decision_id)
            return None

        card.status = DecisionStatus.RESOLVED
        card.resolved_at = response.responded_at or utcnow()
        self.save_decision(card)
        return card

    def list_pending_decisions(self, household_id: str) -> list[DecisionCard]:
        return [
            card
            for raw in self._read_all("decisions")
            if (card := DecisionCard.model_validate(raw)).household_id == household_id
            and card.status is DecisionStatus.PENDING
        ]

    # -- activity ----------------------------------------------------------

    def write_activity(self, entry: ActivityEntry) -> None:
        self._write("activity", entry.entry_id, entry.model_dump_json(indent=2))

    def list_activity(self, household_id: str) -> list[ActivityEntry]:
        entries = [ActivityEntry.model_validate(raw) for raw in self._read_all("activity")]
        return sorted(
            (entry for entry in entries if entry.household_id == household_id),
            key=lambda entry: entry.occurred_at,
        )

    # -- policies ----------------------------------------------------------

    def list_policies(self, household_id: str) -> list[Policy]:
        return [
            policy
            for raw in self._read_all("policies")
            if (policy := Policy.model_validate(raw)).household_id == household_id
        ]

    def save_policy(self, policy: Policy) -> None:
        self._write("policies", policy.policy_id, policy.model_dump_json(indent=2))

    # -- runs --------------------------------------------------------------

    def save_run(self, run: Run) -> None:
        self._write("runs", run.run_id, run.model_dump_json(indent=2))

    def get_run(self, run_id: str) -> Run | None:
        raw = self._read("runs", run_id)
        return Run.model_validate_json(raw) if raw else None


def build_activity_entry(
    action: ProposedAction,
    *,
    risk: RiskTier,
    was_autonomous: bool,
    succeeded: bool,
    summary: str | None = None,
    rationale: str,
    policy_id: str | None = None,
    decision_id: str | None = None,
    error: str | None = None,
) -> ActivityEntry:
    """Build the audit line for one action.

    Every action produces one of these — autonomous or not, success or failure.
    That is a product promise, not a debugging aid (`agent/AGENTS.md`, rule 3).
    """
    return ActivityEntry(
        entry_id=new_id("ent"),
        household_id=action.household_id,
        run_id=action.run_id,
        action_id=action.action_id,
        decision_id=decision_id,
        occurred_at=utcnow(),
        summary=(summary or action.summary)[:160],
        rationale=rationale,
        risk=risk,
        was_autonomous=was_autonomous,
        policy_id=policy_id,
        succeeded=succeeded,
        error=error,
        impact=action.estimated_impact,
    )


def build_store(mode: str | None = None) -> Store:
    """Pick a store. Mock mode is the default and needs no credentials."""
    resolved = (mode or os.environ.get("QH_PROVIDER_MODE") or "mock").strip().casefold()
    if resolved == "live":
        raise NotImplementedError(
            "DynamoStore lands with A7. Run with QH_PROVIDER_MODE=mock until then."
        )
    return JsonStore()
